### ISSUE TITLE
Touchpoints: Submit transaction fails on research recruiter form 

### ISSUE THREAD

**Issue by asarazor** [uswds/uswds-site#1192]
## Description

The Touchpoints recruiter form accessed from the bottom of `/next` doesn't work. Submitting fails due to a JavaScript error.

## Steps to reproduce the issue

1. Go to the final section on [Transforming the American digital experience](https://designsystem.digital.gov/next/#section-5)
2. Tab the Stay in Touch button
3. Fill out the form with:
   - Name
   - Email
   - Select an option
4. Tab Submit: the form silently fails

## Additional information [optional]

- OS: Windows
- Browser: Edge 89.0

## Screenshot of Error in Dev Tools

![image](https://user-images.githubusercontent.com/19854/112466841-acb48d00-8d3c-11eb-805e-c81c023570fa.png)

## Notes

This is a bug in [Touchpoints](https://github.com/GSA/touchpoints), which I have not informed them about. I felt it best to alert the USWDS team as it impacts your users.

While the root cause gets worked on, I suspect you can work around it by recreating the form in your admin interface (I have some experience with Touchpoints).

**Comment by afeijoo** [comment]
@asarazor Thanks for reporting this bug. I can reproduce it and I'm investigating a fix.

**Comment by ryanwoldatwork** [comment]
I'm looking into this. There is a question associated with this form that is not appearing in the UI.

**Comment by ryanwoldatwork** [comment]
This is now resolved.

In Touchpoints:
A Form has many Form Sections.
And Form Sections have many Questions.

A Question was still associated with the Form, but not showing in the UI because it was associated with a Form Section that no longer existed; essentially orphaning the question and resulting in the error.

This bug has been noted in the Touchpoints backlog and prioritized. A regression test will be written when addressing this.

Thank you for reporting this!

**Comment by afeijoo** [comment]
Thanks for fixing this, @ryanwoldatwork! I successfully submitted a response on the form.
