### ISSUE TITLE
Encoding mismatch on page

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1408]
You have an encoding mismatch on your web page that causes, for example,
what I assume are supposed to be quotes appear instead  as Â.  From
https://designsystem.digital.gov/components/text-input/:

The problem in this case appears to be in your uswds-custom.css file,
line 3773 (which also shouldn't include a space after the character):

**Comment by amyleadem** [comment]
@brunerae Are there screenshots or other details for this item? We are not seeing an issue on Chrome, Firefox, Safari, or IE. I just want to ensure that I am looking in the right spot.

**Comment by brunerae** [comment]
Hi @amyleadem! I do -- I've attached here
![lnyFxIPdy34nVfJW](https://user-images.githubusercontent.com/90786981/151086280-38e8589d-c86d-4443-a100-d54184f278e3.png)
![wD0NpEEigcHGcprg](https://user-images.githubusercontent.com/90786981/151086283-d3944d88-4682-4da1-bf3b-3a040952272f.png)

!

**Comment by amyleadem** [comment]
I am not able to replicate this. I have checked on IE11, Firefox 96, Chrome 97, Safari 15.2 and everything appears as expected.

@brunerae Do we have any browser information for this bug?

@mejiaj @mahoneycm Are you able to see this bug? Do you have any ideas? 

A bit of a shot in the dark but wondering if it might be caused by a personal browser setting that is overriding the declared utf-8.

**Comment by amyleadem** [comment]
@brunerae Do we have any browser information for this bug?

I have tested on Chrome 97, Firefox 96, Safari 15.2, and IE11 and everything appears as expected. 

I was not able to see the issue natively but it did appear when I did a manual override in the browser to force encoding with windows-1252 or ISO-8859 (there might be others). 

Without more information, I suspect that this is caused by a personal browser setting that is overriding the declared UTF-8. It might require the user resetting their text encoding. 

@mejiaj @mahoneycm Any thoughts?

**Comment by mejiaj** [comment]
Looks like the right entity to me in the SCSS. `utf-8` encoding is set by default in SASS. I agree with @amyleadem, we need more info.

What browser are they using? Are they or some org policy overriding the character encoding?

https://github.com/uswds/uswds-site/blob/7b99a3297f36bc91a4989c2902193c2eb261056f/css/_uswds-theme-custom-styles.scss#L1177-L1185

**Comment by thisisdano** [comment]
Closed since we cannot reproduce
