### ISSUE TITLE
Batch PRs for 3.0 Site content updates

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#1510]
After completing an audit, make a batch of PRs for anything that needs to be updated on Site after 3.0

**Comment by mejiaj** [comment]
@mikki-stacey @bonnieAcameron there's this base branch created [v3-content-updates](https://github.com/uswds/uswds-site/tree/v3-content-updates), when making changes please select the second option and create a new branch to start a pull request. 

The branch you'll want to merge to will be v3-content-updates, instead of main.

![image](https://user-images.githubusercontent.com/3385219/162068541-a3ac822f-84c5-4c19-92ac-cc99faff3ba4.png)
