### ISSUE TITLE
USWDS-Site - Bug: "Touchpoints 'was this page helpful?' button z-index overlaps in-page navigation on uswds components page"

### ISSUE THREAD

**Issue by nick-mon1** [uswds/uswds-site#1999]
### Describe the bug

The "Was this page helpful?" button has `z-index: 500` which overlaps the "In this page" in-page navigation `z-index:100` on the [uswds components page](https://designsystem.digital.gov/components/overview/). This prevents links from being clickable adjacent to the touch points button.

### Steps to reproduce the bug

1. [Visit components overview page](https://designsystem.digital.gov/components/overview/)
2. Move mouse over the `in-page navigation` links next to the "Was this page helpful" button
3. They are not clickable

### Expected Behavior

These adjacent links should be clickable

### Screenshots

https://user-images.githubusercontent.com/104778659/217942588-c705944a-1921-4aad-86e2-aa0da2d7eb0a.mov

https://user-images.githubusercontent.com/104778659/217942724-349a4e95-c388-40ff-bc68-22045815dc04.mov

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by danbrady** [comment]
It appears the issue is with the `.touchpoints__container` wrapper around the button (seen as purple in the screen above). It is set with `position:sticky` and positions the button to the right with flexbox. The wrapper blocks all pointer-events of elements underneath even if it has a transparent background. This isn't limited to blocking just in-page navigation links, but any element that's behind that wrapper. (The same issue happens to links in side navigation as well.) 

One idea for a fix is to add to the `.touchpoints__container` wrapper `pointer-events:none;` which will allow links underneath to be clickable. However, that will prevent any events within the wrapper, like the 'Was this helpful?' button. So then put the pointer-events back to all descendent elements with something like `.touchpoints_container > * { pointer-events: all; }`. But admittedly, this feels a little heavy-handed.

**Comment by mahoneycm** [comment]
Is there another page that this bug is viewable on? I haven't been able to reproduce the bug
