### ISSUE TITLE
USWDS-Site - Compile: Clarify dot notation for nested settings

### ISSUE THREAD

**Issue by jfredrickson5** [uswds/uswds-site#2116]
### Describe the bug

I'm not sure if this is an issue with USWDS Compile or if it's an issue with USWDS itself due to the variable names it uses.

When I attempt to customize USWDS settings by editing `_uswds-theme.scss` to configure a setting that has a period in its name (e.g., `$flex-settings.responsive`), it causes an error.

```
[styles] Compiling with USWDS 3.3.0
[styles] sass/_uswds-theme.scss
[styles] Error: expected ":".
[styles]    ╷
[styles] 33 │   $flex-settings.responsive: true,
[styles]    │                 ^
[styles]    ╵
[styles]   sass/_uswds-theme.scss 33:17  @forward
[styles]   sass/styles.scss 1:1          root stylesheet
```

The `$flex-settings.responsive` variable is documented [here](https://designsystem.digital.gov/utilities/flex/) (see Advanced settings > Responsive variants -> Utility variable).

### Steps to reproduce the bug

1. Install USWDS and USWDS Compile
2. Run `gulp init` to install the initial USWDS Compile files
3. Edit `_uswds-theme.scss` to add a setting that contains a period in the name

Example:
```
@use "uswds-core" with (
  $flex-settings.responsive: true
);
```

4. Run `gulp compile`

This will output an error regarding the variable name.

### Expected Behavior

USWDS Compile should successfully compile USWDS with my custom settings.

### System setup

```
"@uswds/compile": "^1.0.0",
"@uswds/uswds": "^3.3.0",
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-compile/issues) for duplicate bug reports.

**Comment by amyleadem** [comment]
Hello @jfredrickson5, I apologize for the delayed response on this. I’m afraid it got a little lost in triage between the repos. 

When you see setting declared in dot notation like this, it indicates that it is a nested setting inside of a Sass map. 

That means that if you wanted to turn on responsive styles for `$flex-settings`, your [USWDS settings configuration](https://designsystem.digital.gov/documentation/settings/#configuring-custom-uswds-settings) would look something like this:

```
@use "uswds-core" with (
  $flex-settings: (
    output: true, //default
    responsive: true,
  )
);
```

Please note that this example includes `output:true` in the configuration because it would automatically be set to `false` if you only declared `responsive:true` in your `$flex-settings` configuration. This is default Sass behavior, but the forthcoming USWDS 3.5.0 release will make this experience simpler. With 3.5.0, you will be able to declare only the settings you wish to change without it affecting the defaults (More details in https://github.com/uswds/uswds/pull/5216). 

I am transferring this issue over to our documentation site repo so that we can clarify that settings indicated with dot notation indicate a mapped setting. 

If you have any questions, don’t hesitate to reach out.

**Comment by jfredrickson5** [comment]
That makes sense, thank you for the clarification!
