### ISSUE TITLE
USWDS-Site - Bug: Accordion state not reading accurately in JAWS

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds-site#2368]
### Describe the bug

The audible announcement of the "expanded" and "collapsed" state of the accordions on the component pages says "to activate press enter". It Should say "Expanded" or "collapsed".

Here is a [screen recording of the accordion](https://app.screencast.com/zrHtktVIR9TNE) in use on a component pages vs. the accordion example.

This issue is only evident in JAWS. It announces correctly in NVDA.

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/accordion/
2. Open JAWS (if you have it)
3.  Open the "component preview" accordion. Hit enter to close the accordion. Hit enter again to open it.
4. Listen for "to activate press enter"

### Expected Behavior

JAWS should say "collapsed" and "expanded". 

It does say this in the actual component example that's inside the accordion.

### System setup

PC
Desktop
Chrome
JAWS

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds-site/issues) for duplicate bug reports.

**Comment by amyleadem** [comment]
@amycole501 @alex-hull Can you test this with JAWS in our Storybook instance so that we can figure out if it is happening with the base code? Here are the related links:

- [Accordion component - default ](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/iframe.html?args=&id=components-accordion--default&viewMode=story)(Storybook)
- [Accordion component - mulitselect](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.sites.pages.cloud.gov/preview/uswds/uswds/develop/iframe.html?args=&id=components-accordion--multiselectable&viewMode=story) (Storybook)

**Comment by amycole501** [comment]
Both storybook items announce "expanded" and "collapsed"

**Comment by amycole501** [comment]
Also, checked the accordion on vote.gov and it sounds good as well. I hear 'expanded' and 'collapsed'. https://vote.gov/

**Comment by alex-hull** [comment]
Checked on USA.gov and they read correctly as well. Tested on USWDS' site on component preview accordions for button and date picker and they are reading "to activate press enter" after the first keyboard interaction.

**Comment by brunerae** [comment]
Assigning to next Sprint so we can fully understand the bug and begin to wrap our heads around a possible solution.
