### ISSUE TITLE
Content Audit: Automate a repeatable process

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-site#2411]
We have outlined the following goals for this content audit of the [USWDS website](https://designsystem.digital.gov/):
- Gather basic descriptive and performance data for all pages
- Combine with top tasks results
- Identify obsolete and redundant content
- Gauge and report on site’s adherence to web content best practices
- Gauge and report on site’s adherence to accessibility best practices
- Use data to inform IA and content improvements

[Documents related to the content audit](https://drive.google.com/drive/folders/1XU8xm1nUGG0VU1ogPZUfXkKQdXsbZss_?usp=drive_link) of the USWDS website are located in the project Google Drive.

In order to consider the task of automating a repeatable process done, the following tasks should be done:

- [ ] Team has aligned on which audit tasks can be automated and which must be manual
- [ ] Automations have been implemented in a place where the team can reference them
- [ ] Instructions for manual audit processes have been documented clearly in a place where they are available to the team

**Comment by sarah-sch** [comment]
Tentatively proposing the following ideas for implementing a repeatable process. They are [documented in this presentation](https://docs.google.com/presentation/d/1D_qSevvRKA715_83XYiqEq_FhZh32iadGDhp8S8giXI/edit?usp=sharing), which will be discussed in person with the team so that we can align.

- Document process for merging Screaming Frog and Google Analytics data
- Review all pages at least annually
- TTS governance review + 25% of remaining pages per quarter
- Involve full team to leverage technical expertise
- Incorporate Siteimprove reports

**Comment by thisisdano** [comment]
Thank you!

**Comment by annepetersen** [comment]
@finekatie, just bringing this to your attention in case you hadn't seen it in awhile

**Comment by finekatie** [comment]
Thanks @annepetersen  - it says the issue is closed. Is there something new to revisit?

**Comment by annepetersen** [comment]
Just checking in to see if we're still using this repeatable process.

**Comment by finekatie** [comment]
Katie to research/revisit and provide some feedback. New issues may emerge from this.
