### ISSUE TITLE
Set up requirements for next TTS quarterly content review deadline

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-site#2640]
### Background
To operationalize our content audit, we need to comply with TTS quarterly content reviews in addition to reviewing 25% of the remaining pages on the site (those not covered by TTS requirements) per quarter. 

The next review deadline will be **Friday, June 28, 2024**.

### Purpose
The purpose of this issue is to organize work for the next content audit including review instructions and a list of pages that will be reviewed before the June 28 deadline.

### Steps
- [x] Ensure that all stats and notes on [2024 audit sheet](https://docs.google.com/spreadsheets/d/1ZDYHJa7Xq5GT0ZWQNVrEHVQkIR5aOg0gVKWdiy8g45I/edit?usp=sharing) are up to date
- [x] Prepare instructions for reviewers to reference during quarterly review process
- [x] Identify page to be reviewed by Friday, June 7, 2024

**Comment by sarah-sch** [comment]
@finekatie and @annepetersen met on 6/8/2024 to discuss which pages would be reviewed as part of TTS audit. Follow up to confirm on 6/10/2024.

**Comment by finekatie** [comment]
Met with Ashley on 6/17 to refine. Met with Anne again on 6/26 to further refine and decide what pages we're adding to Q3:
https://designsystem.digital.gov/
https://designsystem.digital.gov/about/
https://designsystem.digital.gov/about/community/
https://designsystem.digital.gov/about/whats-new/
https://designsystem.digital.gov/documentation/accessibility/

This is about ready to go. Since deadline has been extended, Katie will follow up with Ashley to determine a send date.

**Comment by annepetersen** [comment]
This probably isn't the right issue to note this, but I submitted [this quarter's form](https://docs.google.com/spreadsheets/d/1KPPHXr5YhV2Zyl-c9fZh6NB-kKgXyzgBZyIhio-97OA/edit?gid=2127860789#gid=2127860789) just now.

**Comment by brunerae** [comment]
Closing this as done.
