### ISSUE TITLE
We may be building styleguide.scss twice

### ISSUE THREAD

**Issue by toolness** [uswds/uswds-site#335]
While trying to make the site build faster in #334, I noticed that Jekyll seems to be analyzing both `css/styleguide.scss` *and* `assets/css/styleguide.scss`, which appear to be the same file because I think the gulp `copy-doc-styles` task is copying them over. In the final built site it looks like `css/styleguide.css` and `assets/css/styleguide.css` both exist and are the same too.

I think that different layouts/templates in the site might refer to different `styleguide.css`s.

I am not sure why this is happening and I'm also not 100% sure I'm correct about this, but it sure is confusing.

**Comment by maya** [comment]
@donjo do you know if this was fixed in https://github.com/18F/web-design-standards-docs/pull/458, specifically @toolness' comment https://github.com/18F/web-design-standards-docs/pull/458#discussion_r155871609.

**Comment by donjo** [comment]
@maya I think there are more instances of things being built/compiled more times than they need to be so I'll keep this open for now since it contains things that will get addressed when we take a closer look at `npm test` and what happens when you run that command. (And breaking it up into separate parts in the Circle config)
