### ISSUE TITLE
Basic header demo not working properly

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-site#662]
There's some added space between the button and its menu, and I wonder if it's coming from some custom styles or from an unintended interaction with base element styling.

It looks like it's coming from some `ol, ul` styles — how can we prevent these styles from affecting the menu, regardless of settings?

<img width="1051" alt="screen shot 2018-10-05 at 9 43 15 am" src="https://user-images.githubusercontent.com/11464021/46548231-4a712480-c883-11e8-9454-9c1722fb776b.png">

**Comment by saracope** [comment]
It looks like this is happening because **_.usa-nav-submenu_** does not have any margin set. As a result, the base ul style is getting applied which gives it a 1em margin and create the gap shown. 

Possible fix: add margin-top (& margin-bottom?) of zero to **_.usa-nav-submenu_**. @thisisdano 

![basic-header](https://user-images.githubusercontent.com/2197515/47151658-5cea5580-d2a8-11e8-8fe4-a552c40f81d6.gif)

**Comment by saracope** [comment]
@thisisdano 
'[usa-nav-submenu](https://github.com/uswds/uswds/blob/4cf1f9b1a34b225d40015669d5135cebcc26d3a9/src/stylesheets/components/_navigation.scss#L288)' is calling the 'add-list-reset' mixin. Do you think it makes sense to add the margin to this mixin? Or would that cause too many side effects?

**Proposed change:**
```
@mixin add-list-reset {
  @include u-margin-y(0);
  list-style-type: none;
  padding-left: 0;
}
```

**Comment by thisisdano** [comment]
Hm — I like the change and I think it's worth testing. I don't really know what the effect will be, but I think we should check it out
