### ISSUE TITLE
Improve 18F form text on USWDS Community Page

### ISSUE THREAD

**Issue by jeremyzilar** [uswds/uswds-site#851]
Would be great to have a community page on the USWDS site, similar to https://digital.gov/communities/uswds/ that gives more context about joining the USWDS community.

- I often am not sure where I should link to when telling people to join the USWDS community. I feel like the Digital.gov page is the better option at the moment. https://digital.gov/communities/uswds/
- On the USWDS site, the link to join the community is quite small at the bottom of USWDS pages
- Once clicked, I am taking to an 18F form (out of the USWDS context). Having it better explained on a page before clicking would help. [Our page on Digital.gov](https://digital.gov/communities/uswds/) does that to some extent, but it too can be better.

**Comment by thisisdano** [comment]
We have a community page now (https://designsystem.digital.gov/about/community/) but the link off to the 18F google form is still disruptive and weird. Let's update the content on the Community page to better set expectations.

**Comment by bonnieAcameron** [comment]
I was just chatting with the team about this last week. I think that we may need to archive this one, since the core of the problem will be addressed in the top tasks/audit findings. The improvement will come as part of that effort. If you agree, feel free to archive, if not, let's have a discussion at our next team meeting.
